channels:
  - pytorch
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - cuml==22.12.00[build=cuda11_py38*]
  - numpy==1.23.5
  - pytorch==1.13.1[build=py3.8_cuda11.6*]
  - pip
  - pip:
    - click
